name = "TinyCA"
uuid = "39e091e7-18e7-4ee7-aef2-9a5c586df47e"
authors = ["Yusheng Zhao <yushengzhao2020@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
